root: true
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
  - import
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - prettier
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:import/recommended
  - plugin:import/typescript
settings:
  react:
    version: detect
rules:
  camelcase: off
  import/no-unresolved: off
  import/order:
    - error
    - alphabetize: {order: asc}
      newlines-between: never
  react/display-name: off
  react/prop-types: off
  react/react-in-jsx-scope: off
  sort-imports: off
  '@typescript-eslint/no-shadow': off
